### ISSUE TITLE
[BUG] glib: Slice::push(..) doesn't work on instances initialized using Slice::new()

### ISSUE THREAD

**Issue by rmnscnce** [gtk-rs/gtk-rs-core#1075]
**Bug description**

Meanwhile, the ones initialized using `Slice::from([..])` can be pushed on to just fine.

Happens on code compiled with both rustc `1.68.2 (9eb3afe9e 2023-03-27)` and `1.70.0-nightly (88fb1b922 2023-04-10)` on `stable-x86_64-unknown-linux-gnu`.

Minimal reproduction code:
```rs
// This doesn't crash
let mut slice_0: glib::Slice<glib::Date> = glib::Slice::from([
	glib::Date::from_dmy(12, glib::DateMonth::April, 2023).unwrap(),
	glib::Date::from_dmy(13, glib::DateMonth::April, 2023).unwrap(),
	glib::Date::from_dmy(14, glib::DateMonth::April, 2023).unwrap(),
]);
slice_0.push(glib::Date::from_dmy(15, glib::DateMonth::April, 2023).unwrap());

// This one crashes
let mut slice_1: glib::Slice<glib::Date> = glib::Slice::new();
slice_1.push(glib::Date::from_dmy(12, glib::DateMonth::April, 2023).unwrap()); // ! segmentation fault
```

**Backtrace**

`rust-gdb` backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x000055555555dbb4 in core::ptr::write<glib::date::Date> (dst=0x4, src=glib::date::Date {inner: glib_sys::GDate {julian_days: 1431655860, flags_dmy: 8287282}})
    at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ptr/mod.rs:1354

[ ..snip.. ]

#0  0x000055555555dbb4 in core::ptr::write<glib::date::Date> (dst=0x4, src=glib::date::Date {inner: glib_sys::GDate {julian_days: 1431655860, flags_dmy: 8287282}})
    at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ptr/mod.rs:1354
#1  0x000055555555c7dd in glib::collections::slice::Slice<glib::date::Date>::push<glib::date::Date> (self=0x7fffffffd600, item=glib::date::Date {inner: glib_sys::GDate {julian_days: 1431655860, flags_dmy: 8287282}})
    at /var/home/user/devel/gtk-rs/gtk-rs-core/glib/src/collections/slice.rs:740
#2  0x000055555555cd95 in glib_test::main () at src/main.rs:15
        slice_1 = glib::collections::slice::Slice<glib::date::Date> {ptr: core::ptr::non_null::NonNull<glib_sys::GDate> {pointer: 0x4}, len: 0, capacity: 0}
        slice_0 = glib::collections::slice::Slice<glib::date::Date> {ptr: core::ptr::non_null::NonNull<glib_sys::GDate> {pointer: 0x5555555af240}, len: 4, capacity: 32}
```

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/1076
