### ISSUE TITLE
[BUG] gstreamer-audio-sys fails tests on s390x

### ISSUE THREAD

**Issue by werdahias** [gtk-rs/gtk-rs-core#1106]
Uploading the gstreamer-rs stack I found that the tests for gstreamer-audio-sys fail on s390x because of the difference in endianness:

```
    Finished test [unoptimized + debuginfo] target(s) in 9.90s
     Running `/tmp/tmp.30db5T5qQX/target/s390x-unknown-linux-gnu/debug/deps/gstreamer_audio_sys-ea1c83d09bbf0c25`

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running `/tmp/tmp.30db5T5qQX/target/s390x-unknown-linux-gnu/debug/deps/abi-9f95b83dc152bfdb`

running 2 tests
test cross_validate_layout_with_c ... ok
test cross_validate_constants_with_c ... FAILED

failures:

---- cross_validate_constants_with_c stdout ----
Constant value mismatch for (gint) GST_AUDIO_FORMAT_F32
Rust: "28"
C:    "29"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_F64
Rust: "30"
C:    "31"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_S16
Rust: "4"
C:    "5"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_S18
Rust: "24"
C:    "25"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_S20
Rust: "20"
C:    "21"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_S24
Rust: "16"
C:    "17"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_S24_32
Rust: "8"
C:    "9"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_S32
Rust: "12"
C:    "13"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_U16
Rust: "6"
C:    "7"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_U18
Rust: "26"
C:    "27"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_U20
Rust: "22"
C:    "23"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_U24
Rust: "18"
C:    "19"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_U24_32
Rust: "10"
C:    "11"
Constant value mismatch for (gint) GST_AUDIO_FORMAT_U32
Rust: "14"
C:    "15"
thread 'cross_validate_constants_with_c' panicked at 'FAILED: 179 passed; 14 failed', tests/abi.rs:108:13
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: abi::Results::expect_total_success
             at ./tests/abi.rs:108:13
   3: abi::cross_validate_constants_with_c
             at ./tests/abi.rs:145:5
   4: abi::cross_validate_constants_with_c::{{closure}}
             at ./tests/abi.rs:115:1
   5: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    cross_validate_constants_with_c

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.50s


```
Version is 0.19.4

For now I can work around this issue with a `#[cfg(not(target_arch = "s390x"))]` ; I know this is not the best solution.

**Comment by sdroege** [comment]
Wrong place for the issue :) Here would be better https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/issues/new

I think the correct fix here is to ignore these constants. In `gstreamer-audio/src/audio_format.rs` they're alraedy handled correctly based on the endianness. I'll take care of that later.

> For now I can work around this issue with a `#[cfg(not(target_arch = "s390x"))]` ; I know this is not the best solution.

The more correct fix would be `#[cfg(target_endian = "little")]`

**Comment by sdroege** [comment]
Let's track that in https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/1270 then
