### ISSUE TITLE
[BUG] 32bit arch tests fail for graphene-sys

### ISSUE THREAD

**Issue by werdahias** [gtk-rs/gtk-rs-core#1107]
I recently uploaded gtk-rs 0.5 to debian experimental. The tests for graphene-sys fail on all 32-bit arches: armel, armhf, i386 and s390x. They do pass on arm64, amd64 and ppc64.
Relevant log: 

```
    Finished test [unoptimized + debuginfo] target(s) in 21.08s
     Running `/tmp/tmp.9QdXoDssmz/target/armv7-unknown-linux-gnueabihf/debug/deps/graphene_sys-298709175a568412`

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running `/tmp/tmp.9QdXoDssmz/target/armv7-unknown-linux-gnueabihf/debug/deps/abi-60a97b557f3a4f7c`

running 2 tests
test cross_validate_layout_with_c ... FAILED
test cross_validate_constants_with_c ... ok

failures:

---- cross_validate_layout_with_c stdout ----
Layout mismatch for graphene_simd4x4f_t
Rust: Layout { size: 64, alignment: 16 }
C:    Layout { size: 64, alignment: 4 }
thread 'cross_validate_layout_with_c' panicked at 'FAILED: 20 passed; 1 failed', tests/abi.rs:107:13
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: abi::Results::expect_total_success
             at ./tests/abi.rs:107:13
   3: abi::cross_validate_layout_with_c
             at ./tests/abi.rs:179:5
   4: abi::cross_validate_layout_with_c::{{closure}}
             at ./tests/abi.rs:149:1
   5: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    cross_validate_layout_with_c

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.23s
```

**Comment by sdroege** [comment]
This seems kind of related to https://github.com/gtk-rs/gtk-rs-core/pull/1105

**Comment by werdahias** [comment]
armel:

```

running 2 tests
test cross_validate_layout_with_c ... FAILED
test cross_validate_constants_with_c ... ok

failures:

---- cross_validate_layout_with_c stdout ----
Layout mismatch for graphene_simd4x4f_t
Rust: Layout { size: 64, alignment: 16 }
C:    Layout { size: 64, alignment: 4 }
thread 'cross_validate_layout_with_c' panicked at 'FAILED: 20 passed; 1 failed', tests/abi.rs:107:13
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: abi::Results::expect_total_success
             at ./tests/abi.rs:107:13
   3: abi::cross_validate_layout_with_c
             at ./tests/abi.rs:179:5
   4: abi::cross_validate_layout_with_c::{{closure}}
             at ./tests/abi.rs:149:1
   5: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    cross_validate_layout_with_c

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.42s
```

i386:

```
running 2 tests
test cross_validate_layout_with_c ... FAILED
test cross_validate_constants_with_c ... ok

failures:

---- cross_validate_layout_with_c stdout ----
Layout mismatch for graphene_simd4f_t
Rust: Layout { size: 16, alignment: 16 }
C:    Layout { size: 16, alignment: 4 }
Layout mismatch for graphene_simd4x4f_t
Rust: Layout { size: 64, alignment: 16 }
C:    Layout { size: 64, alignment: 4 }
thread 'cross_validate_layout_with_c' panicked at 'FAILED: 19 passed; 2 failed', tests/abi.rs:107:13
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: abi::Results::expect_total_success
             at ./tests/abi.rs:107:13
   3: abi::cross_validate_layout_with_c
             at ./tests/abi.rs:179:5
   4: abi::cross_validate_layout_with_c::{{closure}}
             at ./tests/abi.rs:149:1
   5: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    cross_validate_layout_with_c

```
s390x: 

```
running 2 tests
test cross_validate_layout_with_c ... FAILED
test cross_validate_constants_with_c ... ok

failures:

---- cross_validate_layout_with_c stdout ----
Layout mismatch for graphene_simd4x4f_t
Rust: Layout { size: 64, alignment: 16 }
C:    Layout { size: 64, alignment: 8 }
thread 'cross_validate_layout_with_c' panicked at 'FAILED: 20 passed; 1 failed', tests/abi.rs:107:13
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: abi::Results::expect_total_success
             at ./tests/abi.rs:107:13
   3: abi::cross_validate_layout_with_c
             at ./tests/abi.rs:180:5
   4: abi::cross_validate_layout_with_c::{{closure}}
             at ./tests/abi.rs:150:1
   5: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    cross_validate_layout_with_c
```

**Comment by sdroege** [comment]
Thanks!
