### ISSUE TITLE
[BUG} Regression: test failure on s390x for png feature of cairo-rs

### ISSUE THREAD

**Issue by werdahias** [gtk-rs/gtk-rs-core#1391]
**Bug description**
Test failure on s390x for png feature of cairo-rs. The recent upload of cairo-rs 0.19.4 caused its autopkgtest to regress.
I will add a patch for now so this test gets skipped.

LOG:

```

test enums::tests::stride_panics_on_bad_value - should panic ... ok
350s test surface_png::tests::valid_png_reads_correctly ... FAILED
350s 
350s failures:
350s 
350s ---- surface_png::tests::valid_png_reads_correctly stdout ----
350s thread 'surface_png::tests::valid_png_reads_correctly' panicked at 'assertion failed: `(left == right)`
350s   left: `255`,
350s  right: `42`', src/surface_png.rs:192:9
350s stack backtrace:
350s    0: rust_begin_unwind
350s              at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
350s    1: core::panicking::panic_fmt
350s              at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:67:14
350s    2: core::panicking::assert_failed_inner
350s    3: core::panicking::assert_failed
350s              at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:228:5
350s    4: cairo::surface_png::tests::valid_png_reads_correctly
350s              at ./src/surface_png.rs:192:9
350s    5: cairo::surface_png::tests::valid_png_reads_correctly::{{closure}}
350s              at ./src/surface_png.rs:170:36
350s    6: core::ops::function::FnOnce::call_once
350s              at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
350s    7: core::ops::function::FnOnce::call_once
350s              at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
350s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
350s 
350s 
350s failures:
350s     surface_png::tests::valid_png_reads_correctly
350s 
350s test result: FAILED. 26 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s
350s 
350s error: test failed, to rerun pass `--lib`
350s autopkgtest [08:42:14]: test librust-cairo-rs-dev:png: -----------------------]
```

**Comment by sdroege** [comment]
You mean 0.19.3 was working correctly?

**Comment by werdahias** [comment]
not, unfortunately 0.19.4 was the first version where I observed this (coming from 0.18.5)

**Comment by sdroege** [comment]
Well, this test also existed back then so it must've worked before. Can you `git bisect` this maybe?
