### ISSUE TITLE
[BUG] `call_with_unix_fd_list_future` crashes if fd list is empty

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk-rs-core#1599]
According to C docs the fd list can be null. And it looks like it is if the server put nothing in the fd list.

https://docs.gtk.org/gio/method.DBusProxy.call_with_unix_fd_list_finish.html

gtk-rs doesn't expect it to be null and chrashes

```
thread 'main' panicked at /home/herold/Projects/gtk-rs-core/gio/src/auto/unix_fd_list.rs:8:1:
assertion failed: !ptr.is_null()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x55748870986a - std::backtrace_rs::backtrace::libunwind::trace::h99efb0985cae5d78
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x55748870986a - std::backtrace_rs::backtrace::trace_unsynchronized::he2c1aa63b3f7fad8
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55748870986a - std::sys::backtrace::_print_fmt::h8a221d40f5e0f88b
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:66:9
   3:     0x55748870986a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:39:26
   4:     0x557488725efb - core::fmt::rt::Argument::fmt::h5da9c218ec984eaf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/rt.rs:177:76
   5:     0x557488725efb - core::fmt::write::hf5713710ce10ff22
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/mod.rs:1178:21
   6:     0x5574887073e3 - std::io::Write::write_fmt::hda708db57927dacf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/io/mod.rs:1823:15
   7:     0x55748870aa12 - std::sys::backtrace::BacktraceLock::print::hbcdbec4d97c91528
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:42:9
   8:     0x55748870aa12 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:266:22
   9:     0x55748870a67e - std::panicking::default_hook::h81c8cd2e7c59ee33
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:293:9
  10:     0x55748870b20f - std::panicking::rust_panic_with_hook::had2118629c312a4a
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:797:13
  11:     0x55748870af53 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:664:13
  12:     0x557488709d49 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:170:18
  13:     0x55748870ac14 - rust_begin_unwind
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
  14:     0x5574886957e5 - core::panicking::panic_nounwind_fmt::runtime::h1c669551f619867f
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:112:18
  15:     0x5574886957e5 - core::panicking::panic_nounwind_fmt::hc0ae93930ea8f76c
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:122:5
  16:     0x557488695872 - core::panicking::panic_nounwind::h9f485ff9b02bac75
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:221:5
  17:     0x557488695a36 - core::panicking::panic_cannot_unwind::hea865182d7ce50af
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:310:5
  18:     0x5574886ad701 - gio::auto::dbus_proxy::DBusProxyExt::call_with_unix_fd_list::call_with_unix_fd_list_trampoline::hf851164a6b1b91d2
                               at /home/herold/Projects/gtk-rs-core/gio/src/auto/dbus_proxy.rs:413:9
  19:     0x7f75d00bf433 - g_task_return_now
                               at ./debian/build/deb/../../../gio/gtask.c:1361:7
  20:     0x7f75d00c00d3 - g_task_return
                               at ./debian/build/deb/../../../gio/gtask.c:1430:15
  21:     0x7f75d00c00d3 - g_task_return
                               at ./debian/build/deb/../../../gio/gtask.c:1387:1
  22:     0x7f75d012b2bc - reply_cb
                               at ./debian/build/deb/../../../gio/gdbusproxy.c:2555:7
  23:     0x7f75d00bf433 - g_task_return_now
                               at ./debian/build/deb/../../../gio/gtask.c:1361:7
  24:     0x7f75d00c00d3 - g_task_return
                               at ./debian/build/deb/../../../gio/gtask.c:1430:15
  25:     0x7f75d00c00d3 - g_task_return
                               at ./debian/build/deb/../../../gio/gtask.c:1387:1
  26:     0x7f75d011de62 - g_dbus_connection_call_done
                               at ./debian/build/deb/../../../gio/gdbusconnection.c:6346:5
  27:     0x7f75d00bf433 - g_task_return_now
                               at ./debian/build/deb/../../../gio/gtask.c:1361:7
  28:     0x7f75d00bf46d - complete_in_idle_cb
                               at ./debian/build/deb/../../../gio/gtask.c:1375:3
  29:     0x7f75cfeaf7df - g_main_dispatch
                               at ./debian/build/deb/../../../glib/gmain.c:3357:28
  30:     0x7f75cfeb1a17 - g_main_context_dispatch_unlocked
                               at ./debian/build/deb/../../../glib/gmain.c:4208:7
  31:     0x7f75cfeb1a17 - g_main_context_iterate_unlocked
                               at ./debian/build/deb/../../../glib/gmain.c:4273:5
  32:     0x7f75cfeb2180 - g_main_context_iteration
                               at ./debian/build/deb/../../../glib/gmain.c:4338:12
  33:     0x7f75d00ef445 - g_application_run
                               at ./debian/build/deb/../../../gio/gapplication.c:2715:7
  34:     0x5574886a97b6 - gio::application::ApplicationExtManual::run_with_args::h93556566c879651e
                               at /home/herold/Projects/gtk-rs-core/gio/src/application.rs:24:13
  35:     0x5574886a9899 - gio::application::ApplicationExtManual::run::h94a19f827cbae39e
                               at /home/herold/Projects/gtk-rs-core/gio/src/application.rs:17:9
  36:     0x55748869a15e - dbus::main::h25d7b3d4851e9bd5
                               at /home/herold/tmp/dbus/src/main.rs:28:5
  37:     0x5574886aa3bb - core::ops::function::FnOnce::call_once::h7e9086e0d849ca08
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
  38:     0x55748869b46e - std::sys::backtrace::__rust_begin_short_backtrace::h4232b237cd3d262a
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:154:18
  39:     0x55748869a741 - std::rt::lang_start::{{closure}}::hdcc43b21a68f3b58
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:164:18
  40:     0x557488703f60 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h08ecba131ab90ec4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:284:13
  41:     0x557488703f60 - std::panicking::try::do_call::hf33a59fd8ce953f4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  42:     0x557488703f60 - std::panicking::try::h5005ce80ce949fd8
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  43:     0x557488703f60 - std::panic::catch_unwind::hfbae19e2e2c5b7ed
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  44:     0x557488703f60 - std::rt::lang_start_internal::{{closure}}::ha0331c3690741813
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:48
  45:     0x557488703f60 - std::panicking::try::do_call::hcdcbdb616b4d0295
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  46:     0x557488703f60 - std::panicking::try::h3f2f1725a07d2256
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  47:     0x557488703f60 - std::panic::catch_unwind::h51869e04b56b2dc3
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  48:     0x557488703f60 - std::rt::lang_start_internal::h4d90db0530245041
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:20
  49:     0x55748869a71a - std::rt::lang_start::hdd4d2205800d47ba
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:163:17
  50:     0x55748869a1be - main
  51:     0x7f75cfc5bd68 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  52:     0x7f75cfc5be25 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  53:     0x5574886960f1 - _start
  54:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
Aborted (core dumped)
```

**Comment by sophie-h** [comment]
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4429

**Comment by sophie-h** [comment]
And it's merged

**Comment by sdroege** [comment]
We should get that once the GNOME SDK is updated, which should happen soonish :) Thanks!

I'll close this one here once it's integrated. Unless you need a fast fix and we should temporarily work around it?

**Comment by sophie-h** [comment]
> Unless you need a fast fix and we should temporarily work around it?

For now I can add that locally if I need it

**Comment by sdroege** [comment]
Ok, shouldn't take more than a few days anyway :)
