### ISSUE TITLE
gio: Windows CI fails with access violation

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#57]
CC @pbor 

```
running 37 tests
test cancellable::check_callback ... ok
test input_stream::tests::into_input_stream ... ok
test input_stream::tests::read ... ok
test input_stream::tests::read_all ... ok
test input_stream::tests::read_async ... ok
test input_stream::tests::read_all_async ... ok
test input_stream::tests::read_bytes_async ... ok
test input_stream::tests::skip_async ... ok
test input_stream::tests::std_io_read ... ok
test memory_input_stream::tests::add_bytes ... ok
test memory_input_stream::tests::async_buf_read ... ok
test memory_input_stream::tests::async_read ... ok
test memory_input_stream::tests::from_bytes ... ok
test memory_input_stream::tests::new ... ok
test memory_input_stream::tests::read_async_future ... ok
test memory_output_stream::tests::steal ... ok
test memory_output_stream::tests::steal_empty ... ok
test output_stream::tests::into_output_stream ... ok
test output_stream::tests::splice_async ... ok
test output_stream::tests::std_io_write ... ok
test output_stream::tests::write_all_async ... ok
test output_stream::tests::write_async ... ok
test output_stream::tests::write_bytes_async ... ok
test read_input_stream::tests::test_read ... ok
test read_input_stream::tests::test_read_seek ... ok
test settings::test::bool_set_get ... ok
test settings::test::string_get ... ok
test settings::test::wrong_type ... ok
error: test failed, to rerun pass '--lib'
Error: test failed, to rerun pass '--lib'
Caused by:
  process didn't exit successfully: `D:\a\gtk-rs-core\gtk-rs-core\target\debug\deps\gio-55580ae740cbf346.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
Error: The process 'C:\Rust\.cargo\bin\cargo.exe' failed with exit code 3221225477
```

**Comment by sdroege** [comment]
Well, it also fails for me on Linux :clown_face:

**Comment by sdroege** [comment]
```
gio::subclass::seekable::seekable_seek<gio::subclass::input_stream::tests::imp::SimpleInputStream> (seekable=0x7ffff0005880, offset=0, type_=2, cancellable=0x0, err=0x0)
    at gio/src/subclass/seekable.rs:211
211	            *err = e.into_raw();
(gdb) bt
#0  gio::subclass::seekable::seekable_seek<gio::subclass::input_stream::tests::imp::SimpleInputStream> (seekable=0x7ffff0005880, offset=0, type_=2, cancellable=0x0, err=0x0)
    at gio/src/subclass/seekable.rs:211
#1  0x00007ffff7dc9128 in g_input_stream_real_skip (stream=0x7ffff0005880 [SimpleInputStream], count=2, cancellable=0x0, error=0x7ffff7697d38) at ../../../gio/ginputstream.c:423
#2  0x0000555555600d3b in gio::subclass::input_stream::{{impl}}::parent_skip<gio::subclass::input_stream::tests::imp::SimpleInputStream>
    (self=0x7ffff0005830, stream=0x7ffff7697e18, count=2, cancellable=...) at gio/src/subclass/input_stream.rs:129
#3  0x0000555555600ac4 in gio::subclass::input_stream::InputStreamImpl::skip<gio::subclass::input_stream::tests::imp::SimpleInputStream>
    (self=0x7ffff0005830, stream=0x7ffff7697e18, count=2, cancellable=...) at gio/src/subclass/input_stream.rs:33
#4  0x000055555560ea9e in gio::subclass::input_stream::stream_skip<gio::subclass::input_stream::tests::imp::SimpleInputStream> (ptr=0x7ffff0005880, count=2, cancellable=0x0, err=0x7ffff7697f38)
    at gio/src/subclass/input_stream.rs:234
#5  0x00007ffff7dcaa31 in g_input_stream_skip (stream=0x7ffff0005880 [SimpleInputStream], count=2, cancellable=0x0, error=0x7ffff7697f38) at ../../../gio/ginputstream.c:391
#6  0x0000555555616fce in gio::auto::input_stream::{{impl}}::skip<gio::subclass::input_stream::tests::SimpleInputStream,gio::auto::cancellable::Cancellable>
    (self=0x7ffff76980b8, count=2, cancellable=...) at gio/src/auto/input_stream.rs:289
#7  0x00005555555e3c6c in gio::subclass::input_stream::tests::test_simple_stream () at gio/src/subclass/input_stream.rs:363
#8  0x000055555561705a in gio::subclass::input_stream::tests::test_simple_stream::{{closure}} () at gio/src/subclass/input_stream.rs:353
```
