### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by andy128k** [gtk-rs/gtk-rs-core#64]
Running `cargo test` gives

```
     Running tests/abi.rs (target/debug/deps/abi-46b59376a247bea1)

running 2 tests
In file included from tests/layout.c:5:
tests/manual.h:3:10: fatal error: gio/gdesktopappinfo.h: No such file or directory
    3 | #include <gio/gdesktopappinfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from tests/constant.c:5:
tests/manual.h:3:10: fatal error: gio/gdesktopappinfo.h: No such file or directory
    3 | #include <gio/gdesktopappinfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
test cross_validate_layout_with_c ... FAILED
test cross_validate_constants_with_c ... FAILED

failures:

---- cross_validate_layout_with_c stdout ----
thread 'cross_validate_layout_with_c' panicked at 'called `Result::unwrap()` on an `Err` value: "compilation command \"cc\" \"-Wno-deprecated-declarations\" \"-std=c11\" \"-D__USE_MINGW_ANSI_STDIO\" \"-pthread\" \"-I/usr/include/libmount\" \"-I/usr/include/blkid\" \"-I/usr/include/glib-2.0\" \"-I/usr/lib/x86_64-linux-gnu/glib-2.0/include\" \"tests/layout.c\" \"-o\" \"/tmp/abiqhL4A1/layout\" failed, exit code: 1"', gio/sys/tests/abi.rs:156:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- cross_validate_constants_with_c stdout ----
thread 'cross_validate_constants_with_c' panicked at 'called `Result::unwrap()` on an `Err` value: "compilation command \"cc\" \"-Wno-deprecated-declarations\" \"-std=c11\" \"-D__USE_MINGW_ANSI_STDIO\" \"-pthread\" \"-I/usr/include/libmount\" \"-I/usr/include/blkid\" \"-I/usr/include/glib-2.0\" \"-I/usr/lib/x86_64-linux-gnu/glib-2.0/include\" \"tests/constant.c\" \"-o\" \"/tmp/abiGg0Baw/constant\" failed, exit code: 1"', gio/sys/tests/abi.rs:116:39


failures:
    cross_validate_constants_with_c
    cross_validate_layout_with_c

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass '-p gio-sys --test abi'
```

Adding `"gio-unix-2.0"` to a list of packages in `gio/sys/tests/abi.rs` doesn't help. There are even more errors there.

**Comment by GuillaumeGomez** [comment]
Which OS are you using?

**Comment by andy128k** [comment]
Debian Sid

**Comment by GuillaumeGomez** [comment]
Stupid question but: do you have the `-dev` libraries installed?

**Comment by andy128k** [comment]
I do have them.

**Comment by andy128k** [comment]
Removing `gio/sys/tests` reveals next error. Now it is in `glib/sys`

```
     Running tests/abi.rs (target/debug/deps/abi-76b45a6b1b12f588)

running 2 tests
tests/constant.c: In function ‘main’:
tests/constant.c:812:20: error: ‘G_WIN32_MSG_HANDLE’ undeclared (first use in this function)
  812 |     PRINT_CONSTANT(G_WIN32_MSG_HANDLE);
      |                    ^~~~~~~~~~~~~~~~~~
tests/constant.c:10:22: note: in definition of macro ‘PRINT_CONSTANT’
   10 |     printf(_Generic((CONSTANT_NAME), \
      |                      ^~~~~~~~~~~~~
tests/constant.c:812:20: note: each undeclared identifier is reported only once for each function it appears in
  812 |     PRINT_CONSTANT(G_WIN32_MSG_HANDLE);
      |                    ^~~~~~~~~~~~~~~~~~
tests/constant.c:10:22: note: in definition of macro ‘PRINT_CONSTANT’
   10 |     printf(_Generic((CONSTANT_NAME), \
      |                      ^~~~~~~~~~~~~
test cross_validate_constants_with_c ... FAILED
test cross_validate_layout_with_c ... FAILED

failures:

---- cross_validate_constants_with_c stdout ----
thread 'cross_validate_constants_with_c' panicked at 'called `Result::unwrap()` on an `Err` value: "compilation command \"cc\" \"-Wno-deprecated-declarations\" \"-std=c11\" \"-D__USE_MINGW_ANSI_STDIO\" \"-I/usr/include/glib-2.0\" \"-I/usr/lib/x86_64-linux-gnu/glib-2.0/include\" \"tests/constant.c\" \"-o\" \"/tmp/abij6WCLP/constant\" failed, exit code: 1"', glib/sys/tests/abi.rs:116:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- cross_validate_layout_with_c stdout ----
Layout mismatch for GTestLogMsg
Rust: Layout { size: 24, alignment: 8 }
C:    Layout { size: 32, alignment: 8 }
thread 'cross_validate_layout_with_c' panicked at 'FAILED: 107 passed; 1 failed', glib/sys/tests/abi.rs:107:13


failures:
    cross_validate_constants_with_c
    cross_validate_layout_with_c

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.16s

error: test failed, to rerun pass '-p glib-sys --test abi'
```

**Comment by GuillaumeGomez** [comment]
I'm pretty sure the `G_WIN32_*` items shouldn't be included in those tests on non-windows targets. Weird...

cc @sdroege

**Comment by andy128k** [comment]
## gobject-sys: 

```
     Running tests/abi.rs (target/debug/deps/abi-2e94c062022842e9)

running 2 tests
test cross_validate_layout_with_c ... ok
test cross_validate_constants_with_c ... FAILED

failures:

---- cross_validate_constants_with_c stdout ----
Constant value mismatch for G_TYPE_FUNDAMENTAL_MAX
Rust: "255"
C:    "1020"
thread 'cross_validate_constants_with_c' panicked at 'FAILED: 58 passed; 1 failed', glib/gobject-sys/tests/abi.rs:107:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    cross_validate_constants_with_c

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.16s

error: test failed, to rerun pass '-p gobject-sys --test abi'
```

IMHO, this one reveals an issue in gobject-introspection. I believe that 1020 is the [correct value](https://gitlab.gnome.org/GNOME/glib/-/blob/master/gobject/gtype.h#L210).

```
$ grep -B 2 'G_TYPE_FUNDAMENTAL_MAX' /usr/share/gir-1.0/GObject-2.0.gir 
    <constant name="TYPE_FUNDAMENTAL_MAX"
              value="255"
              c:type="G_TYPE_FUNDAMENTAL_MAX">
```

## Graphene

```

     Running tests/abi.rs (target/debug/deps/abi-38e9ff4fc77cd6b4)

running 2 tests
tests/constant.c: In function ‘main’:
tests/constant.c:61:20: error: ‘GRAPHENE_HAS_GCC’ undeclared (first use in this function); did you mean ‘GRAPHENE_HAS_SSE’?
   61 |     PRINT_CONSTANT(GRAPHENE_HAS_GCC);
      |                    ^~~~~~~~~~~~~~~~
tests/constant.c:10:22: note: in definition of macro ‘PRINT_CONSTANT’
   10 |     printf(_Generic((CONSTANT_NAME), \
      |                      ^~~~~~~~~~~~~
tests/constant.c:61:20: note: each undeclared identifier is reported only once for each function it appears in
   61 |     PRINT_CONSTANT(GRAPHENE_HAS_GCC);
      |                    ^~~~~~~~~~~~~~~~
tests/constant.c:10:22: note: in definition of macro ‘PRINT_CONSTANT’
   10 |     printf(_Generic((CONSTANT_NAME), \
      |                      ^~~~~~~~~~~~~
tests/constant.c:10:21: error: ‘_Generic’ selector of type ‘float’ is not compatible with any association
   10 |     printf(_Generic((CONSTANT_NAME), \
      |                     ^
tests/constant.c:64:5: note: in expansion of macro ‘PRINT_CONSTANT’
   64 |     PRINT_CONSTANT(GRAPHENE_PI);
      |     ^~~~~~~~~~~~~~
tests/constant.c:10:21: error: ‘_Generic’ selector of type ‘float’ is not compatible with any association
   10 |     printf(_Generic((CONSTANT_NAME), \
      |                     ^
tests/constant.c:65:5: note: in expansion of macro ‘PRINT_CONSTANT’
   65 |     PRINT_CONSTANT(GRAPHENE_PI_2);
      |     ^~~~~~~~~~~~~~
test cross_validate_constants_with_c ... FAILED
test cross_validate_layout_with_c ... ok

failures:

---- cross_validate_constants_with_c stdout ----
thread 'cross_validate_constants_with_c' panicked at 'called `Result::unwrap()` on an `Err` value: "compilation command \"cc\" \"-Wno-deprecated-declarations\" \"-std=c11\" \"-D__USE_MINGW_ANSI_STDIO\" \"-mfpmath=sse\" \"-msse\" \"-msse2\" \"-I/usr/include/graphene-1.0\" \"-I/usr/lib/x86_64-linux-gnu/graphene-1.0/include\" \"-I/usr/include/glib-2.0\" \"-I/usr/lib/x86_64-linux-gnu/glib-2.0/include\" \"tests/constant.c\" \"-o\" \"/tmp/abiv9g3qw/constant\" failed, exit code: 1"', graphene/sys/tests/abi.rs:114:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    cross_validate_constants_with_c

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.20s

error: test failed, to rerun pass '-p graphene-sys --test abi'
```

I have `libgraphene-1.0-dev` version 1.10.4 installed.

## pango-sys

```
     Running tests/abi.rs (target/debug/deps/abi-e7b5eeae3530eb45)

running 2 tests
test cross_validate_layout_with_c ... ok
test cross_validate_constants_with_c ... FAILED

failures:

---- cross_validate_constants_with_c stdout ----
Constant value mismatch for PANGO_VERSION_MIN_REQUIRED
Rust: "2"
C:    "77312"
thread 'cross_validate_constants_with_c' panicked at 'FAILED: 266 passed; 1 failed', pango/sys/tests/abi.rs:107:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    cross_validate_constants_with_c

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.22s

error: test failed, to rerun pass '-p pango-sys --test abi'
```

Again, looks like an issue in gir files. 

```
$ grep -B 2 -A 1 'PANGO_VERSION_MIN_REQUIRED' /usr/share/gir-1.0/Pango-1.0.gir 
    <constant name="VERSION_MIN_REQUIRED"
              value="2"
              c:type="PANGO_VERSION_MIN_REQUIRED"
              version="1.42">
```

Pango uses `G_ENCODE_VERSION` so, for a version 1.46 correct value is `65536 * 1 + 46 * 256 = 77312`.

**Comment by andy128k** [comment]
I created a PR with Github Actions to verify these errors, but due to [an ongoing incident](https://www.githubstatus.com/incidents/zbpwygxwb3gw) it will take some time to verify.

**Comment by sdroege** [comment]
The -sys tests are currently known to be broken (or rather: not always working), and for example (for many of the crates) you have to run them against the exact same version the .gir file is from. For the reason you just found out: there are version number constants.

The solution for that would be to ignore the version number constants.

**Comment by decathorpe** [comment]
I'm trying to update the gtk-rs crates on Fedora, and I think I'm hitting the same issue .. for example, in glib-sys:

```
---- cross_validate_layout_with_c stdout ----
Layout mismatch for GTestLogMsg
Rust: Layout { size: 24, alignment: 8 }
C:    Layout { size: 32, alignment: 8 }
thread 'cross_validate_layout_with_c' panicked at 'FAILED: 107 passed; 1 failed', tests/abi.rs:107:13
```

I'm also getting the issue about `G_WIN32_MSG_HANDLE undeclared`.

Are these (especially the memory layout mismatch) failures that I can safely ignore for now?

**Comment by sdroege** [comment]
> ---- cross_validate_layout_with_c stdout ----
> Layout mismatch for GTestLogMsg
> Rust: Layout { size: 24, alignment: 8 }
> C:    Layout { size: 32, alignment: 8 }

This probably always failed.

```cpp
typedef struct {
  GTestLogType  log_type;
  guint         n_strings;
  gchar       **strings; /* NULL terminated */
  guint         n_nums;
  long double  *nums;
} GTestLogMsg;
```

Rust doesn't support `long double` (i.e. 128 bit floating pointer numbers).

**Comment by sdroege** [comment]
I.e. the Rust side is wrong but it probably does not matter as nothing could've ever used that safely.
