### ISSUE TITLE
[BUG] Calling `extend_from_slice` on an empty `gio::ListStore` causes integer underflow panic

### ISSUE THREAD

**Issue by elomatreb** [gtk-rs/gtk-rs-core#640]
**Bug description**

This program panics:
```rs
fn main() {
    let store = gio::ListStore::new(glib::Type::OBJECT);
    let slice: &[glib::Object] = &[];
    store.extend_from_slice(slice);
}
```

The panic is caused by [this subtraction](https://github.com/gtk-rs/gtk-rs-core/blob/fd9efd06a13c865cc3d213bf9700177e32e4c91a/gio/src/list_store.rs#L66).

**Backtrace**

<details><summary>Backtrace</summary>

```
thread 'main' panicked at 'attempt to subtract with overflow', /home/elomatreb/Work/gtk-rs-core/gio/src/list_store.rs:66:21
stack backtrace:
   0:     0x5628b917d3ed - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5628b917d3ed - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5628b917d3ed - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5628b917d3ed - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5628b9199d5c - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x5628b9179ff8 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x5628b917ee87 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5628b917ee87 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5628b917ee87 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x5628b917eb50 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x5628b917f6d9 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x5628b917f389 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:586:13
  12:     0x5628b917d8b4 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5628b917f0d9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x5628b9198ec3 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x5628b9198d0d - core::panicking::panic::h4241c5ccea17faca
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
  16:     0x5628b9169275 - gio::list_store::<impl gio::auto::list_store::ListStore>::extend_from_slice::h20b5433e43dbe371
                               at /home/elomatreb/Work/gtk-rs-core/gio/src/list_store.rs:66:21
  17:     0x5628b9169304 - giotest::main::h584fc08622d88f40
                               at /home/elomatreb/Work/giotest/src/main.rs:4:5
  18:     0x5628b9168edb - core::ops::function::FnOnce::call_once::hb4c0390f17faf887
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  19:     0x5628b916903e - std::sys_common::backtrace::__rust_begin_short_backtrace::h46150e406ace14c0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:122:18
  20:     0x5628b9168fa1 - std::rt::lang_start::{{closure}}::he4f77b919e7502ae
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:145:18
  21:     0x5628b917cad1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb7014f43484a8b4e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  22:     0x5628b917cad1 - std::panicking::try::do_call::h7bc9dc436daeb8c7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  23:     0x5628b917cad1 - std::panicking::try::h653d68a27ff5f175
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  24:     0x5628b917cad1 - std::panic::catch_unwind::h9d739f9f59895e68
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  25:     0x5628b917cad1 - std::rt::lang_start_internal::{{closure}}::hf006f2bc7ce22bbe
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  26:     0x5628b917cad1 - std::panicking::try::do_call::hfb39d6df61a2e69f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  27:     0x5628b917cad1 - std::panicking::try::h13e2d225134958ac
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  28:     0x5628b917cad1 - std::panic::catch_unwind::h3bd49b5a5dfb1a50
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  29:     0x5628b917cad1 - std::rt::lang_start_internal::h2ba92edce36c035e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  30:     0x5628b9168f70 - std::rt::lang_start::h089bd95aec966196
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:144:17
  31:     0x5628b916935c - main
  32:     0x7f45d5138310 - __libc_start_call_main
  33:     0x7f45d51383c1 - __libc_start_main@GLIBC_2.2.5
  34:     0x5628b9168dd5 - _start
  35:                0x0 - <unknown>
```

</details>

**Comment by sdroege** [comment]
Indeed, that could just be a `saturating_sub(1)`. Do you want to provide a PR for this?

**Comment by elomatreb** [comment]
I wasn't sure if that subtraction is correct, since the `AsRef` impl doesn't have it at all for basically the same usecase

**Comment by ranfdev** [comment]
Since `Extend` passes the tests, I think we can remove the `-1`
