### ISSUE TITLE
ListStore::extend_from_slice() panics with empty store

### ISSUE THREAD

**Issue by ebassi** [gtk-rs/gtk-rs-core#649]
**Bug description**

Calling:

```rust
store = gio::ListStore::new(SomeObject::static_type());
store.extend_from_slice(some_vector);
```

will produce a panic.

**Backtrace**

```
thread 'main' panicked at 'attempt to subtract with overflow', /var/home/ebassi/.var/app/org.gnome.Builder/cache/gnome-builder/projects/amberol/builds/io.bassi.Amberol.Devel.json-flatpak-org.gnome.Platform-master-x86_64-main/cargo-home/registry/src/github.com-1ecc6299db9ec823/gio-0.15.7/src/list_store.rs:66:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: gio::list_store::<impl gio::auto::list_store::ListStore>::extend_from_slice
             at ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/amberol/builds/io.bassi.Amberol.Devel.json-flatpak-org.gnome.Platform-master-x86_64-main/cargo-home/registry/src/github.com-1ecc6299db9ec823/gio-0.15.7/src/list_store.rs:66:21
   4: amberol::audio::queue::Queue::add_songs
             at ./Projects/amberol/src/audio/queue.rs:135:9
   5: amberol::window::Window::add_folders_to_queue
             at ./Projects/amberol/src/window.rs:342:17
   6: amberol::window::Window::add_folder::{{closure}}
             at ./Projects/amberol/src/window.rs:292:21
   7: <O as gtk4::auto::native_dialog::NativeDialogExt>::connect_response::response_trampoline
             at ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/amberol/builds/io.bassi.Amberol.Devel.json-flatpak-org.gnome.Platform-master-x86_64-main/cargo-home/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.6/src/auto/native_dialog.rs:172:13
   8: g_cclosure_marshal_VOID__BOOLEANv
   9: <unknown>
  10: g_signal_emit_valist
  11: g_signal_emit
  12: <unknown>
  13: <unknown>
  14: g_main_context_dispatch
  15: <unknown>
  16: g_main_context_iteration
  17: g_application_run
  18: <O as gio::application::ApplicationExtManual>::run_with_args
             at ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/amberol/builds/io.bassi.Amberol.Devel.json-flatpak-org.gnome.Platform-master-x86_64-main/cargo-home/registry/src/github.com-1ecc6299db9ec823/gio-0.15.7/src/application.rs:30:13
  19: <O as gio::application::ApplicationExtManual>::run
             at ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/amberol/builds/io.bassi.Amberol.Devel.json-flatpak-org.gnome.Platform-master-x86_64-main/cargo-home/registry/src/github.com-1ecc6299db9ec823/gio-0.15.7/src/application.rs:23:9
  20: amberol::main
             at ./Projects/amberol/src/main.rs:55:24
  21: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
```

The issue is caused by the implementation of `gio::ListStore::extend_from_slice()`:

```rust
self.splice(self.n_items() - 1, 0, additions)
```

`gio::ListModel::n_items()` returns an `u32` value; if it is zero, trying to subtract 1 from it will overflow.

A plausible fix would be:

```rust
match self.n_items() {
  0 => self.splice(0, 0, additions),
  _ => self.splice(self.n_items() - 1, 0, additions),
};
```

**Comment by sdroege** [comment]
That was fixed a few days ago in https://github.com/gtk-rs/gtk-rs-core/pull/642 . I'll do a bugfix release this weekend if possible.

**Comment by ebassi** [comment]
Ah, good to know!
