### ISSUE TITLE
[BUG] gobject panics on `NULL` property retrieval

### ISSUE THREAD

**Issue by philn** [gtk-rs/gtk-rs-core#732]
**Bug description**

I'm working a bit on the gtk4 port of glide and noticed that if I attempt to access the GstPlayer `current-video-track` before the pipeline has pre-rolled I get a crash. On C side the corresponding `get_property` code can indeed set a NULL GValue, which afaik should be valid, but is not handled in the Rust bindings.

**Backtrace**

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Failed to get cast value to a different type Unexpected None", filename: "/var/home/phil/.cargo-home/git/checkouts/gtk-rs-core-7be42ca38bd6361c/2b3de36/glib/src/object.rs", function: "glib::object", line: 2487 }', /var/home/phil/.cargo-home/git/checkouts/gtk-rs-core-7be42ca38bd6361c/2b3de36/glib/src/object.rs:2493:42
stack backtrace:
   0:     0x558de5b9621d - std::backtrace_rs::backtrace::libunwind::trace::h8e036432725b1c57
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x558de5b9621d - std::backtrace_rs::backtrace::trace_unsynchronized::h4f83092254c85869
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558de5b9621d - std::sys_common::backtrace::_print_fmt::h9728b5e056a3ece3
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x558de5b9621d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h48bb4bd2928827d2
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x558de5bb7dbc - core::fmt::write::h909e69a2c24f44cc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/fmt/mod.rs:1196:17
   5:     0x558de5b934f1 - std::io::Write::write_fmt::h7f4b8ab8af89e9ef
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/io/mod.rs:1654:15
   6:     0x558de5b97925 - std::sys_common::backtrace::_print::hff4838ebf14a2171
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x558de5b97925 - std::sys_common::backtrace::print::h2499280374189ad9
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x558de5b97925 - std::panicking::default_hook::{{closure}}::h8b270fc55eeb284e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:295:22
   9:     0x558de5b97599 - std::panicking::default_hook::h3217e229d6e9d13c
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:314:9
  10:     0x558de5b97ef8 - std::panicking::rust_panic_with_hook::h9acb8048b738d2e0
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:698:17
  11:     0x558de5b97da7 - std::panicking::begin_panic_handler::{{closure}}::h70f3b839526af6dc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:588:13
  12:     0x558de5b966d4 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ecf2cee857fbe0a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x558de5b97ad9 - rust_begin_unwind
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
  14:     0x558de58f2a03 - core::panicking::panic_fmt::h9f8393e7fd56d655
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
  15:     0x558de58f2af3 - core::result::unwrap_failed::h8b88eb424b1f8daa
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
  16:     0x558de59180f4 - core::result::Result<T,E>::unwrap::hebe203ba79cfd1ea
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1078:23
  17:     0x558de59110f7 - <T as glib::object::ObjectExt>::property::h5469566777cca66e
                               at /var/home/phil/.cargo-home/git/checkouts/gtk-rs-core-7be42ca38bd6361c/2b3de36/glib/src/object.rs:2493:9
  18:     0x558de5925764 - glide::channel_player::ChannelPlayer::new::{{closure}}::h33ed6fc832734c60
                               at /var/home/phil/dev/glide/src/channel_player.rs:273:31
  19:     0x558de590cb2a - <O as gdk4::auto::paintable::PaintableExt>::connect_invalidate_contents::invalidate_contents_trampoline::h9b80bb31181ec60d
                               at /var/home/phil/.cargo-home/git/checkouts/gtk4-rs-e74ad56283dfeb5e/0d61be0/gdk4/src/auto/paintable.rs:168:13
  20:     0x7ff087b6cdb0 - g_closure_invoke
  21:     0x7ff087b994d6 - <unknown>
  22:     0x7ff087b89a2e - g_signal_emit_valist
  23:     0x7ff087b89cb3 - g_signal_emit
  24:     0x558de597b16c - <O as gdk4::auto::paintable::PaintableExt>::invalidate_contents::h7239470238246ae4
                               at /var/home/phil/.cargo-home/git/checkouts/gtk4-rs-e74ad56283dfeb5e/0d61be0/gdk4/src/auto/paintable.rs:138:13
  25:     0x558de597362e - gstgtk4::sink::paintable::imp::SinkPaintable::handle_frame_changed::hfab5cb95c9e9a732
                               at /home/phil/dev/rust/gst-plugins-rs/video/gtk4/src/sink/paintable/imp.rs:205:13
  26:     0x558de59a698f - gstgtk4::sink::paintable::SinkPaintable::handle_frame_changed::h2b8abb34c0e9d6d0
                               at /home/phil/dev/rust/gst-plugins-rs/video/gtk4/src/sink/paintable/mod.rs:39:9
  27:     0x558de599de5d - gstgtk4::sink::PaintableSink::do_action::h9c8505a4cfb90989
                               at /home/phil/dev/rust/gst-plugins-rs/video/gtk4/src/sink/mod.rs:95:17
  28:     0x558de5978918 - gstgtk4::sink::PaintableSink::initialize_paintable::{{closure}}::{{closure}}::h1e068df46fcefbf1
                               at /home/phil/dev/rust/gst-plugins-rs/video/gtk4/src/sink/mod.rs:70:39
  29:     0x558de59a1d23 - glib::main_context_channel::dispatch::h5cf8481b45045448
                               at /var/home/phil/.cargo-home/git/checkouts/gtk-rs-core-7be42ca38bd6361c/2b3de36/glib/src/main_context_channel.rs:243:20
  30:     0x7ff087a71faf - g_main_context_dispatch
  31:     0x7ff087ac72c8 - <unknown>
  32:     0x7ff087a6f940 - g_main_context_iteration
  33:     0x7ff086fb3aed - g_application_run
  34:     0x558de59217fa - <O as gio::application::ApplicationExtManual>::run_with_args::h65672ce63a10c21a
                               at /var/home/phil/.cargo-home/git/checkouts/gtk-rs-core-7be42ca38bd6361c/2b3de36/gio/src/application.rs:35:13
  35:     0x558de58fb03d - glide::main::h9b52453950955a4e
                               at /var/home/phil/dev/glide/src/main.rs:812:5
  36:     0x558de593f1fb - core::ops::function::FnOnce::call_once::h5d2dee41994a0c2d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
  37:     0x558de59294ee - std::sys_common::backtrace::__rust_begin_short_backtrace::h204f074f59d9a778
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:122:18
  38:     0x558de5950231 - std::rt::lang_start::{{closure}}::h3804104c44ad39d2
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:145:18
  39:     0x558de5b8e90e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h5f1ba3b861cac230
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:280:13
  40:     0x558de5b8e90e - std::panicking::try::do_call::h4febfdb770eca39d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  41:     0x558de5b8e90e - std::panicking::try::h8b0eac8a7d726dbf
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  42:     0x558de5b8e90e - std::panic::catch_unwind::h11b83c489c0d8394
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  43:     0x558de5b8e90e - std::rt::lang_start_internal::{{closure}}::h63502d2988634103
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:48
  44:     0x558de5b8e90e - std::panicking::try::do_call::h4be475cff12d2aae
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  45:     0x558de5b8e90e - std::panicking::try::h1a3b25b8eaf9ba31
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  46:     0x558de5b8e90e - std::panic::catch_unwind::h224588ada67b9b0b
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  47:     0x558de5b8e90e - std::rt::lang_start_internal::h2807b375c1959759
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:20
  48:     0x558de5950200 - std::rt::lang_start::h9abbefa36599440e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:144:17
  49:     0x558de58fb58c - main
  50:     0x7ff086be8550 - __libc_start_call_main
  51:     0x7ff086be8609 - __libc_start_main_alias_2
  52:     0x558de58f2ca5 - _start
  53:                0x0 - <unknown>
```

**Comment by philn** [comment]
Is this actually expected and should I use `try_property()` ? Apologies for filing an invalid bug if it turns out invalid :)
