### ISSUE TITLE
Panic when returning an Err from a MainContext::block_on

### ISSUE THREAD

**Issue by melix99** [gtk-rs/gtk-rs-core#739]
**Bug description**

An example of what I'm doing to reproduce the crash:

```rust
let ctx = glib::MainContext::default();
let r: Result<(), i32> = ctx.block_on(async {
    Err(2)
});
```

**Backtrace**

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EnterError', /var/home/melix/Projects/telegrand/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/main_context_futures.rs:228:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1078:23
   4: glib::main_context_futures::TaskSource::poll::{{closure}}
             at ./Projects/telegrand/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/main_context_futures.rs:228:30
   5: glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default
             at ./Projects/telegrand/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/main_context.rs:156:12
   6: glib::main_context_futures::TaskSource::poll
             at ./Projects/telegrand/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/main_context_futures.rs:226:9
   7: glib::main_context_futures::TaskSource::dispatch
             at ./Projects/telegrand/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/main_context_futures.rs:67:34
   8: g_main_context_dispatch
   9: <unknown>
  10: g_main_loop_run
  11: glib::auto::main_loop::MainLoop::run
             at ./Projects/telegrand/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/auto/main_loop.rs:51:13
  12: glib::main_context_futures::<impl glib::auto::main_context::MainContext>::block_on
```

**Comment by sdroege** [comment]
Please provide a full runnable testcase in the future. The problem is not in the code snippet you provided but where you place it.

You can't call block_on() from inside the main loop as that would result in a reentrant /recursive main loop.

**Comment by melix99** [comment]
Oops, sorry, the main loop started so far away in the code that I totally forgot about it and I was convinced that the problem was in block_on() itself.
