### ISSUE TITLE
gio::FileExt::load_contents() panicking

### ISSUE THREAD

**Issue by kov** [gtk-rs/gtk-rs-core#93]
With this code:

```rust
#[cfg(test)]
mod test {
    use gio::FileExt;

    #[test]
    fn load_text_resource() {
        let gfile = gio::File::new_for_uri("resource:///resourcetest/test.txt");
        match gfile.load_contents(gio::NONE_CANCELLABLE) {
            Ok((bytes, string)) => {
                assert_eq!(std::str::from_utf8(&bytes).unwrap(), "embedded gresource test");
            },
            Err(e) => panic!("Could not load test file: {}", e),
        }
    }
}
```

I am getting this:

```
thread 'test::load_text_resource' panicked at 'assertion failed: !ptr.is_null()', /home/kov/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.10.3/src/gstring.rs:51:9
stack backtrace:
   0:     0xaaaab6c0d1f0 - std::backtrace_rs::backtrace::libunwind::trace::h5a661ce6459420e9
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0xaaaab6c0d1f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h716fe45a06d222ff
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaab6c0d1f0 - std::sys_common::backtrace::_print_fmt::h6cf7354c8f0a4586
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0xaaaab6c0d1f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::haa9239ffb10ccdb3
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0xaaaab6c2ac5c - core::fmt::write::h63360d84e002ee0e
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/fmt/mod.rs:1094:17
   5:     0xaaaab6c0a258 - std::io::Write::write_fmt::h156ccf4beb8b3a61
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/io/mod.rs:1580:15
   6:     0xaaaab6c0f1cc - std::sys_common::backtrace::_print::hd774934c1173dfbb
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0xaaaab6c0f1cc - std::sys_common::backtrace::print::hfc1c37837567939b
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0xaaaab6c0f1cc - std::panicking::default_hook::{{closure}}::h9a64c4127b6a8905
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:208:50
   9:     0xaaaab6c0ece8 - std::panicking::default_hook::h83131130ceee3872
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:225:9
  10:     0xaaaab6c0f740 - std::panicking::rust_panic_with_hook::hf0e5494f8786b04c
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:591:17
  11:     0xaaaab6c0f330 - std::panicking::begin_panic_handler::{{closure}}::hdd8adbc0832ba586
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:495:13
  12:     0xaaaab6c0d650 - std::sys_common::backtrace::__rust_end_short_backtrace::h84256d2ab39f4435
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:141:18
  13:     0xaaaab6c0f2c4 - rust_begin_unwind
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:493:5
  14:     0xaaaab6bc26c8 - core::panicking::panic_fmt::h1faca7f0776ccde7
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:92:14
  15:     0xaaaab6bc264c - core::panicking::panic::h42538814f37ed591
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:50:5
  16:     0xaaaab6bf450c - glib::gstring::GString::new::h206c4fd4f21033e5
                               at /home/kov/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.10.3/src/gstring.rs:51:9
  17:     0xaaaab6bf45a8 - <glib::gstring::GString as glib::translate::FromGlibPtrFull<*mut u8>>::from_glib_full::h41a7b0e60fe6252d
                               at /home/kov/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.10.3/src/gstring.rs:303:9
  18:     0xaaaab6bf4444 - glib::translate::from_glib_full::h75d465e734585226
                               at /home/kov/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.10.3/src/translate.rs:1312:5
  19:     0xaaaab6bc2f98 - <O as gio::auto::file::FileExt>::load_contents::h18f957433cf5b407
                               at /home/kov/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.9.1/src/auto/file.rs:1524:21
  20:     0xaaaab6bc3100 - gbuild_test::test::load_text_resource::haccf07be111963cc
                               at /home/kov/Projects/gbuild/gbuild-test/src/main.rs:11:15
  21:     0xaaaab6bc2ea4 - gbuild_test::test::load_text_resource::{{closure}}::h72efaa08df8d67d9
                               at /home/kov/Projects/gbuild/gbuild-test/src/main.rs:9:5
  22:     0xaaaab6bc3598 - core::ops::function::FnOnce::call_once::h346b73313ffdc309
                               at /home/kov/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  23:     0xaaaab6be3b84 - core::ops::function::FnOnce::call_once::hc55ce443fced3742
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/ops/function.rs:227:5
  24:     0xaaaab6be3b84 - test::__rust_begin_short_backtrace::h848f981c07ae889e
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/test/src/lib.rs:576:5
  25:     0xaaaab6be2b48 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf4b9e0a90b74962b
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/alloc/src/boxed.rs:1546:9
  26:     0xaaaab6be2b48 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h329ba3ca4e9e977d
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panic.rs:344:9
  27:     0xaaaab6be2b48 - std::panicking::try::do_call::h0f577107c33deda8
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:379:40
  28:     0xaaaab6be2b48 - std::panicking::try::h54c2683f94bcbf1e
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:343:19
  29:     0xaaaab6be2b48 - std::panic::catch_unwind::h46982527398a5bb8
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panic.rs:431:14
  30:     0xaaaab6be2b48 - test::run_test_in_process::he9125b2f9cbb0e42
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/test/src/lib.rs:599:18
  31:     0xaaaab6be2b48 - test::run_test::run_test_inner::{{closure}}::h03e978e79c4af7d6
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/test/src/lib.rs:491:39
  32:     0xaaaab6bc3a8c - test::run_test::run_test_inner::{{closure}}::h4b7279f267e3fc80
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/test/src/lib.rs:518:37
  33:     0xaaaab6bc3a8c - std::sys_common::backtrace::__rust_begin_short_backtrace::hd76551be5f5f6b37
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:125:18
  34:     0xaaaab6bc7ed0 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h19b93764ae48b540
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/thread/mod.rs:481:17
  35:     0xaaaab6bc7ed0 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha5a5d3e0a99da75a
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panic.rs:344:9
  36:     0xaaaab6bc7ed0 - std::panicking::try::do_call::h79750145e6ff3d21
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:379:40
  37:     0xaaaab6bc7ed0 - std::panicking::try::hdc9fff1eb42fe9e6
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:343:19
  38:     0xaaaab6bc7ed0 - std::panic::catch_unwind::hf04d4dd065a9eb62
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panic.rs:431:14
  39:     0xaaaab6bc7ed0 - std::thread::Builder::spawn_unchecked::{{closure}}::h3f82e73161490102
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/thread/mod.rs:480:30
  40:     0xaaaab6bc7ed0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc4df15c79fd174fb
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/ops/function.rs:227:5
  41:     0xaaaab6c12f9c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4fe24de9f5bbe776
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/alloc/src/boxed.rs:1546:9
  42:     0xaaaab6c12f9c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5af96efb6ecd5ce8
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/alloc/src/boxed.rs:1546:9
  43:     0xaaaab6c12f9c - std::sys::unix::thread::Thread::new::thread_start::h9b3b22f61c6bf19e
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys/unix/thread.rs:71:17
  44:     0xffffa3b3d008 - <unknown>
  45:     0xffffa3a6239c - <unknown>
  46:                0x0 - <unknown>
test test::load_text_resource ... FAILED
```

**Comment by sdroege** [comment]
That's fixed in git by https://github.com/gtk-rs/gtk3-rs/pull/307 and was previously reported as https://github.com/gtk-rs/gtk3-rs/issues/305 , and is also fixed in GIO itself now https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1956

The new release with the fixes should be there in a few days.

**Comment by sdroege** [comment]
Also hi kov! :)

**Comment by kov** [comment]
> Also hi kov! :)

\o/ hi there, thanks for all the great work =D
